### ISSUE TITLE
Level end

### ISSUE THREAD

**Issue by phaax** [meepdarknessmeep/neatevolve#2]
MarI/O can't see anything towards the end of a level. I've modified the tilecache size in ram.lua with some success, but I'm unable to get it working all the way to the end.

```
local screens = memory.readbyte(0x5D)

local fixedsize = 27 --is this correct?
local x_size = 16 * screens --horizontal level
local y_size = fixedsize

local levelsettings = memory.readbyte(0x1925)
if (levelsettings ~= 0) and (levelsettings == 0x3 or levelsettings == 0x4 or levelsettings == 0x7 or levelsettings == 0x8 or levelsettings == 0xa or levelsettings == 0xd) then
	y_size = x_size --vertical level
	x_size = fixedsize
end
```

Another issue is that MarI/O is unable to see some enemies (they're not being marked with red color). 
Some examples are Rex and Chargin' Chuck. I've tried to figure out how to fix this with no success. 

I've also made one little improvement. I changed savestate.load(Filename) to savestate.loadslot(1), this makes it much easier to set everything up.

**Comment by phaax** [comment]
Here's my pool file for the SMW level "Yoshi's Island 2" for testing. :)

[SMW.state.pool.txt](https://github.com/meepdarknessmeep/neatevolve/files/1196792/SMW.state.pool.txt)

**Comment by meepen** [comment]
I also noticed this back when I was toying with this script, I believe those bigger enemies are in a different area of the game's memory.

I can't work on it right now, so it will be a bit until this is fixed. In the meantime, if you want to make a pull request that'd be awesome!
